server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: weather_forecasting _system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weather?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
mybatis:
  type-aliases-package: com.itlh.weather.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl